---
- hosts: All
  remote_user: root
  tasks:
    - name: Update
      yum: name=* state=latest
    - name: Software Groups
      yum: 
        name: "@Hardware Monitoring Utilites",
                 "@Performance Tools",
                 "@Development Tools",
                 "@Network File System Client",
                 "@Console Internet Tools",
                 "@Networking Tools",
                 "@System Administration Tools",
                 "@System Management",
                 "@Compatibility Libraries",
                 "@Platform Development" 
        state: latest
    - name: Copy Hosts Files
      
